@RestWithASPNETUdemy_HostAddress = http://localhost:5095

GET {{RestWithASPNETUdemy_HostAddress}}/todos/
Accept: application/json

###

GET {{RestWithASPNETUdemy_HostAddress}}/todos/1
Accept: application/json

###
